brp: Add option parsing.
Add global and target-specific option parsing. So far we just have one
global option, -h help. But the code is in place for more, and for
target-specific options.

diff --git a/brp b/brp
--- a/brp
+++ b/brp
@@ -19,27 +19,25 @@ source "${script_dir}/kconfig.sh"
 
 MAKE=make
 
-# =============================================================================
-# Utility functions
+OPTIONS=(
+  [global]='h'
+)
 
 # ----------------------------------------------------------------------------
 usage() {
   cat <<EOF
-Usage: $program_name <target> [project] [board] <phase>
+Usage: $program_name [options] <target> [target-options] [project] [board] <phase>
+Options are:
+  -h: Show this help message
+
 Phases are defined with a <project>/board/<board>/config/<phase> defconfig file.
-A phase named "sdk" is handled specially in that you will be prompted
-to overwrite it if it already exists.
 <project> is optional if CWD is the project dir.
 <board> is also optional if CWD is the project's board dir.
 Targets are:
-  build: Build the phase. This is the default.
-  menuconfig: Run make menuconfig on the target, saving the minimal defconfig
-    back in the configs directory.
-  oldconfig: Run make oldconfig on the target, saving the minimal defconfig
-    back in the configs directory.
-  clean: Remove the output directory for the phase.
-  linuxup: Update the linux kernel config for the next available version
-    of linux.
+  build:   Build the phase.
+  *config: Run make *config on the target, saving the minimal phase defconfig.
+  clean:   Remove the output directory for the phase.
+  linuxup: Update the linux kernel config to the next version of linux.
   <other>: Other target are passed through to buildroot make.
 EOF
 [[ -z "$1" ]] || exit "$1"
@@ -439,6 +437,11 @@ known_target() {
 }
 
 # ----------------------------------------------------------------------------
+target_has_options() {
+  [[ "$(type -t "handle_${1}_option")" = function ]]
+}
+
+# ----------------------------------------------------------------------------
 run() {
   echo "$@"
   [[ "${dryrun}" -ne 0 ]] || "$@"
@@ -505,7 +508,7 @@ setup() {
 # ----------------------------------------------------------------------------
 parse_args() {
   # Normal usage is:
-  #  brp <target> <project> <board> <config>
+  #  brp [options] <target> [target-options] <project> <board> <config>
   # but we can infer project and board from $PWD if appropriate.
   # If we are in the project dir, then we don't require that arg.
   # If we are in a projects board dir, we don't require those args.
@@ -517,7 +520,15 @@ parse_args() {
     project="${BASH_REMATCH[1]}"
   fi
 
+  parse_options 'global' "$@"
+  shift $((OPTIND-1))
+
+  (($# > 0)) || usage 1 >&2
+
   target="$1"; shift
+  parse_options "${target}" "$@"
+  shift $((OPTIND-1))
+
   (( $# == 3 )) && { project="$1"; shift; }
   (( $# == 2 )) && { board="$1"; shift; }
   phase="$1"
@@ -525,6 +536,45 @@ parse_args() {
   [[ -n "${project}" ]] || usage 1 >&2
   [[ -n "${board}" ]] || usage 1 >&2
   [[ -n "${phase}" ]] || usage 1 >&2
+}
+
+# ----------------------------------------------------------------------------
+parse_options() {
+  target="$1"; shift
+  while getopts ":${OPTIONS[${target}]-}" opt; do
+    handle_getopt_errors "${target}" "${opt}"
+    handle_option "${target}" "${opt}"
+  done
+}
+
+# ----------------------------------------------------------------------------
+handle_option() {
+  if target_has_options "$1"; then
+    handle_${target}_option "${opt}"
+  fi
+}
+
+# ----------------------------------------------------------------------------
+handle_global_option() {
+  case "$1" in
+    h)
+      usage 0
+      ;;
+  esac
+}
+
+# ----------------------------------------------------------------------------
+handle_getopt_errors() {
+  case "$2" in
+    \?)
+      printf 'Invalid %s option: -%s\n\n' "$1" "${OPTARG}" >&2
+      usage 1 >&2
+      ;;
+    :)
+      printf '%s option -%s requires an argument\n\n' "$1" "${OPTARG}" >&2
+      usage 1 >&2
+      ;;
+  esac
 }
 
 # ----------------------------------------------------------------------------
